config/routes.rb
Seeds::Application.routes.draw do
  devise_for :admins

  devise_for :users
  resources :users, :has_one => :lender #:only => [:index, :show]
 
  match "lender", :controller =>"lenders", :action =>"show", :via => :get;

  resources :lenders

  
  root :to => "home#index"

  resources :home

  %w(credit express express_complete complete).each do |action|
    match "purchase/#{action}" => "purchase##{action}"
  end

  
  
  resources :borrowers

  resources :transactions

  resources :badges

  resources :badge_lists

end

app/models/borrower.rb
class Borrower < ActiveRecord::Base
   attr_accessible :first_name, :last_name, :nationalID, :description, :business_type, :gender
end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
  #GET /borrowers
  def index
    @borrowers = Borrower.all
  end
  
  #GET /borrowers/id
  def show
    @borrower = Borrower.find(params[:id])
  end

  #GET /borrowers/new
  def new
    @borrower = Borrower.new
  end

  #GET /borrowers/id/edit
  def edit
    @borrower = Borrower.find(params[:id])
  end
  
  #POST /borrowers
  def create
    @borrower = Borrower.new(params[:borrower])

    if @borrower.save
	    redirect_to @borrower, :notice => 'Borrower was successfully created.'
    else
	    render :action =>'new'
    end
  end
 
  #PUT /borrowers/id
  def update
    @borrower = Borrower.find(params[:id])

    respond_to do |format|
      if @borrower.update_attributes(params[:borrower])
        format.html { redirect_to @borrower, notice: 'Borrower was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @borrower.errors, status: :unprocessable_entity }
      end
    end
  end
  
  #DELETE /borrowers/id
  def destroy
    @borrower = Borrower.find(params[:id])
    @borrower.destroy

    respond_to do |format|
      format.html { redirect_to borrowers_url }
      format.json { head :ok }
    end
  end

end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/views/borrowers/_form.html.erb
<%= form_for(@borrower) do |f| %>
  <% if @borrower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@borrower.errors.count, "error") %> prohibited this borrower from being saved:</h2>

      <ul>
      <% @borrower.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :sum %><br />
    <%= f.number_field :sum %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>


app/views/borrowers/edit.html.erb
<h1>Editing borrower</h1>

<%= render 'form' %>

<%= link_to 'Show', @borrower %> |
<%= link_to 'Back', borrowers_path %>


app/views/borrowers/index.html.erb
<div style="text-align:center">
<h1>Listing borrowers</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Description</th>
    <th>Total Loans</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @borrowers.each do |borrower| %>
  <tr>
    <td><%= borrower.first_name %></td>
    <td><%= borrower.last_name %></td>
    <td><%= borrower.description %></td>
    <td><%= borrower.sum %></td>
    <td><%= link_to 'Show', borrower %></td>
  </tr>
<% end %>
</table>

<br />
</div>


app/views/borrowers/new.html.erb
<h1 style="text-align:center">New borrower</h1>
<%= form_for(@borrower) do |f| %>
  <% if @borrower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@borrower.errors.count, "error") %> prohibited this borrower from being saved:</h2>

      <ul>
      <% @borrower.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div> 

  <div class="field">
    <%= f.label :gender %><br />
    <%= f.select :gender, ['Female', 'Male'] %>
  </div>

  <div class="field">
    <%= f.label :nationaL_ID_number %><br />
    <%= f.text_field :nationalID %>
  </div>

  <div class="field">
    <%= f.label :business_category %><br />
    <%= f.select :business_type, ['Farming', 'Transport', 'Communication', 'Trading', 'Fishing'] %>
  </div>

  <div class="field">
    <%= f.label :brief_description_of_business %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Back', borrowers_path %>

app/views/borrowers/show.html.erb

<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @borrower.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @borrower.last_name %>
</p>

<p>
  <b>Description:</b>
  <%= @borrower.description %>
</p>

<p>
  <b>Loan Amount borrowed: Kshs. </b>
  <%= @borrower.sum %>
</p>

<%= link_to 'Back', borrowers_path %>
