config/routes.rb
Seeds::Application.routes.draw do
  devise_for :admins

  devise_for :users
  resources :users, :has_one => :lender #:only => [:index, :show]
 
  match "lender", :controller =>"lenders", :action =>"show", :via => :get;

  resources :lenders

  
  root :to => "home#index"

  resources :home

  %w(credit express express_complete complete).each do |action|
    match "purchase/#{action}" => "purchase##{action}"
  end

  
  
  resources :borrowers

  resources :transactions

  resources :badges

  resources :badge_lists

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  attr_accessible :BID, :name, :description
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @badges }
    end
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
    @badge = Badge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @badge }
    end
  end

  # GET /badges/new
  # GET /badges/new.json
  def new
    @badge = Badge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @badge }
    end
  end

  # GET /badges/1/edit
  def edit
    @badge = Badge.find(params[:id])
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(params[:badge])

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render json: @badge, status: :created, location: @badge }
      else
        format.html { render action: "new" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /badges/1
  # PUT /badges/1.json
  def update
    @badge = Badge.find(params[:id])

    respond_to do |format|
      if @badge.update_attributes(params[:badge])
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge = Badge.find(params[:id])
    @badge.destroy

    respond_to do |format|
      format.html { redirect_to badges_url }
      format.json { head :ok }
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_form.html.erb
<%= form_for(@badge) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :badge_number %><br />
    <%= f.number_field :BID %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


app/views/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>


app/views/badges/index.html.erb
<h1>Listing badges</h1>

<table>
  <tr>
    <th>Badge Number</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @badges.each do |badge| %>
  <tr>
    <td><%= badge.BID %></td>
    <td><%= badge.name %></td>
    <td><%= badge.description %></td>
    <td><%= link_to 'Show', badge %></td>
  </tr>
<% end %>
</table>




app/views/badges/new.html.erb
<h1>New badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>


app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Badge Number:</b>
  <%= @badge.BID %>
</p>

<p>
  <b>Name:</b>
  <%= @badge.name %>
</p>

<p>
  <b>Description:</b>
  <%= @badge.description %>
</p>


<%= link_to 'Back', badges_path %>
