config/routes.rb
Seeds::Application.routes.draw do
  devise_for :admins

  devise_for :users
  resources :users, :has_one => :lender #:only => [:index, :show]
 
  match "lender", :controller =>"lenders", :action =>"show", :via => :get;

  resources :lenders

  
  root :to => "home#index"

  resources :home

  %w(credit express express_complete complete).each do |action|
    match "purchase/#{action}" => "purchase##{action}"
  end

  
  
  resources :borrowers

  resources :transactions

  resources :badges

  resources :badge_lists

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :ok }
    end
  end
  
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lender_id_number %><br />
    <%= f.number_field :lender_id %>
  </div>
  <div class="field">
    <%= f.label :borrower_id_number %><br />
    <%= f.number_field :borrower_id %>
  </div>
  <div class="field">
    <%= f.label :borrower_amount %><br />
    <%= f.text_field :borrower_amount %>
  </div>
  <div class="field">
    <%= f.label :lender_amount %><br />
    <%= f.datetime_select :lender_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>


app/views/transactions/index.html.erb
<h1 style="text-align:center">Historical Amounts</h1>
<p>Total amounts that lenders have crowd sourced: $. <%= Transaction.sum (:lender_amount) %> </p>
<p>Total amount of loans disbursed to borrowers: Kshs. <%= Transaction.sum (:borrower_amount) %> </p>


app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :borrower_unique_number %><br />
    <%= f.number_field :borrower_id %>
  </div>

  <div class="field">
    <%= f.label :new_amount %><br />
    <%= f.text_field :borrower_amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', transactions_path %>


app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Borrower id:</b>
  <%= @transaction.borrower_id %>
</p>

<p>
  <b>Borrower Amount:</b>
  <%= @transaction.borrower_amount %>
</p>


<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>


